In [2]:
import pandas as pd


# read file
df = pd.read_csv('./FatalitiesMarch2018.csv')
df.head()

,Crash ID,State,Month,Year,Dayweek,Time,Crash_Type,Bus_Involvement,Rigid_Truck_Involvement,Articulated_Truck_Involvement,Speed_Limit,Road_User,Gender,Age
0,20181001,NSW,March,2018,Tuesday,7:18,Multiple vehicle,No,Yes,No,50,Bicyclist (includes pillion passengers),Male,29
1,20181005,NSW,March,2018,Monday,18:25,Multiple vehicle,No,No,No,50,Driver,Male,41
2,20181007,NSW,March,2018,Friday,8:00,Pedestrian,No,No,No,50,Pedestrian,Male,55
3,20181012,NSW,March,2018,Friday,16:05,Multiple vehicle,No,Yes,No,80,Driver,Female,17
4,20181016,NSW,March,2018,Sunday,1:45,Single vehicle,No,No,No,80,Driver,Female,24

In [3]:
# filter out rows where there's -9

df["Age"] = pd.to_numeric(df["Age"]) #convert age to numeric

df[df.Age >0 ] # age cannot be -ve or 0
df.head()

,Crash ID,State,Month,Year,Dayweek,Time,Crash_Type,Bus_Involvement,Rigid_Truck_Involvement,Articulated_Truck_Involvement,Speed_Limit,Road_User,Gender,Age
0,20181001,NSW,March,2018,Tuesday,7:18,Multiple vehicle,No,Yes,No,50,Bicyclist (includes pillion passengers),Male,29
1,20181005,NSW,March,2018,Monday,18:25,Multiple vehicle,No,No,No,50,Driver,Male,41
2,20181007,NSW,March,2018,Friday,8:00,Pedestrian,No,No,No,50,Pedestrian,Male,55
3,20181012,NSW,March,2018,Friday,16:05,Multiple vehicle,No,Yes,No,80,Driver,Female,17
4,20181016,NSW,March,2018,Sunday,1:45,Single vehicle,No,No,No,80,Driver,Female,24

In [4]:
# find out data types
df.dtypes

Crash ID                           int64
State                             object
Month                             object
Year                               int64
Dayweek                           object
Time                              object
Crash_Type                        object
Bus_Involvement                   object
Rigid_Truck_Involvement           object
Articulated_Truck_Involvement     object
Speed_Limit                        int64
Road_User                         object
Gender                            object
Age                                int64
dtype: object

In [5]:
# gender cannot be -9
df[df.Gender != '-9' ]

,Crash ID,State,Month,Year,Dayweek,Time,Crash_Type,Bus_Involvement,Rigid_Truck_Involvement,Articulated_Truck_Involvement,Speed_Limit,Road_User,Gender,Age
0,20181001,NSW,March,2018,Tuesday,7:18,Multiple vehicle,No,Yes,No,50,Bicyclist (includes pillion passengers),Male,29
1,20181005,NSW,March,2018,Monday,18:25,Multiple vehicle,No,No,No,50,Driver,Male,41
2,20181007,NSW,March,2018,Friday,8:00,Pedestrian,No,No,No,50,Pedestrian,Male,55
3,20181012,NSW,March,2018,Friday,16:05,Multiple vehicle,No,Yes,No,80,Driver,Female,17
4,20181016,NSW,March,2018,Sunday,1:45,Single vehicle,No,No,No,80,Driver,Female,24
5,20181022,NSW,March,2018,Saturday,12:45,Single vehicle,No,No,No,80,Motorcycle rider,Male,35
6,20181025,NSW,March,2018,Tuesday,22:00,Single vehicle,No,No,No,100,Driver,Male,22
7,20181026,NSW,March,2018,Monday,20:36,Multiple vehicle,No,No,No,70,Motorcycle rider,Male,20
8,20181027,NSW,March,2018,Friday,16:50,Multiple vehicle,No,No,Yes,110,Driver,Male,46
9,20181028,NSW,March,2018,Friday,23:15,Pedestrian,No,No,No,100,Pedestrian,Female,29
10,20181047,NSW,March,2018,Friday,18:55,Multiple vehicle,No,No,Yes,50,Driver,Male,87
11,20181050,NSW,March,2018,Saturday,15:20,Single vehicle,No,No,No,80,Passenger,Male,17
12,20181052,NSW,March,2018,Saturday,2:50,Single vehicle,No,No,No,50,Driver,Male,35
13,20181053,NSW,March,2018,Wednesday,23:30,Single vehicle,No,No,No,60,Driver,Female,28
14,20181055,NSW,March,2018,Saturday,10:00,Multiple vehicle,No,No,No,100,Motorcycle rider,Male,64
15,20181058,NSW,March,2018,Friday,11:10,Pedestrian,No,No,No,60,Pedestrian,Female,82
16,20181062,NSW,March,2018,Thursday,15:13,Multiple vehicle,No,No,No,80,Passenger,Female,84
17,20181065,NSW,March,2018,Thursday,15:00,Single vehicle,No,No,No,100,Driver,Male,62
18,20181067,NSW,March,2018,Monday,13:43,Multiple vehicle,No,No,No,50,Motorcycle rider,Male,30
19,20181069,NSW,March,2018,Monday,16:30,Single vehicle,No,No,No,60,Driver,Male,71
20,20181071,NSW,March,2018,Sunday,10:55,Multiple vehicle,Yes,No,No,110,Driver,Male,61
21,20181073,NSW,March,2018,Wednesday,1:00,Single vehicle,No,No,No,80,Passenger,Male,30
22,20181075,NSW,March,2018,Monday,20:34,Pedestrian,No,No,No,50,Pedestrian,Male,66
23,20181082,NSW,March,2018,Saturday,20:00,Single vehicle,No,No,No,100,Motorcycle rider,Male,42
24,20181086,NSW,March,2018,Thursday,18:43,Single vehicle,No,No,No,100,Passenger,Male,33
26,20182005,VIC,March,2018,Saturday,5:20,Single vehicle,No,-9,No,60,Driver,Male,26
27,20182008,VIC,March,2018,Wednesday,18:05,Single vehicle,No,-9,No,-9,Driver,Female,68
29,20182011,VIC,March,2018,Friday,13:05,Single vehicle,No,-9,No,-9,Motorcycle rider,Male,60
30,20182013,VIC,March,2018,Thursday,23:30,Single vehicle,No,-9,No,-9,Driver,Male,37
31,20182023,VIC,March,2018,Wednesday,9:25,Pedestrian,Yes,-9,No,40,Pedestrian,Female,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48866,19895090,WA,January,1989,Monday,16:55,Multiple vehicle,No,-9,No,60,Driver,Male,22
48867,19895109,WA,January,1989,Tuesday,17:30,Multiple vehicle,No,-9,No,90,Driver,Male,22
48868,19895120,WA,January,1989,Saturday,5:05,Multiple vehicle,No,-9,No,70,Driver,Female,24
48869,19895121,WA,January,1989,Saturday,15:50,Single vehicle,No,-9,No,100,Passenger,Male,22
48870,19895132,WA,January,1989,Friday,15:45,Single vehicle,No,-9,No,110,Driver,Male,49
48871,19895132,WA,January,1989,Friday,15:45,Single vehicle,No,-9,No,110,Passenger,Female,48
48872,19895142,WA,January,1989,Friday,23:25,Multiple vehicle,No,-9,No,60,Passenger,Male,62
48873,19895167,WA,January,1989,Tuesday,20:55,Multiple vehicle,No,-9,No,60,Motorcycle rider,Male,26
48874,19895210,WA,January,1989,Wednesday,21:00,Multiple vehicle,No,-9,No,-9,Driver,Male,70
48875,19895213,WA,January,1989,Sunday,22:17,Single vehicle,No,-9,No,110,Passenger,Male,19
48876,19895213,WA,January,1989,Sunday,22:17,Single vehicle,No,-9,No,110,Passenger,Male,19
48877,19895214,WA,January,1989,Thursday,18:58,Single vehicle,No,-9,No,50,Passenger,Male,39
48878,19896005,TAS,January,1989,Tuesday,7:00,Multiple vehicle,No,-9,No,100,Driver,Male,18
48879,19896006,TAS,January,1989,Monday,2:10,Single vehicle,No,-9,No,70,Driver,Male,18
48880,19896016,TAS,January,1989,Sunday,19:20,Multiple vehicle,No,-9,No,100,Driver,Male,19
48881,19896018,TAS,January,1989,Tuesday,12:40,Multiple vehicle,No,-9,No,60,Passenger,Female,63
48882,19896027,TAS,January,1989,Wednesday,20:20,Multiple vehicle,No,-9,Yes,100,Driver,Male,18
48883,19896027,TAS,January,1989,Wednesday,20:20,Multiple vehicle,No,-9,Yes,100,Passenger,Female,13
48884,19896027,TAS,January,1989,Wednesday,20:20,Multiple vehicle,No,-9,Yes,100,Passenger,Male,13
48885,19896027,TAS,January,1989,Wednesday,20:20,Multiple vehicle,No,-9,Yes,100,Passenger,Female,14
48886,19896027,TAS,January,1989,Wednesday,20:20,Multiple vehicle,No,-9,Yes,100,Passenger,Female,11
48887,19896027,TAS,January,1989,Wednesday,20:20,Multiple vehicle,No,-9,Yes,100,Passenger,Male,13
48888,19896033,TAS,January,1989,Sunday,19:00,Single vehicle,No,-9,No,100,Driver,Male,23
48889,19896042,TAS,January,1989,Saturday,20:05,Single vehicle,No,-9,No,60,Bicyclist (includes pillion passengers),Male,16
48890,19896046,TAS,January,1989,Monday,22:15,Multiple vehicle,No,-9,No,100,Bicyclist (includes pillion passengers),Male,15
48891,19896065,TAS,January,1989,Saturday,14:30,Single vehicle,No,-9,No,100,Driver,Male,52
48892,19897035,NT,January,1989,Saturday,23:30,Single vehicle,No,-9,Yes,900,Passenger,Female,31
48893,19897045,NT,January,1989,Saturday,11:20,Single vehicle,No,-9,No,900,Passenger,Male,42
48894,19898018,ACT,January,1989,Thursday,22:10,Multiple vehicle,No,-9,No,-9,Passenger,Female,82
48895,19898026,ACT,January,1989,Sunday,0:15,Single vehicle,No,-9,No,-9,Driver,Female,18

In [6]:
# road user cannot be 9 or -9
df[df.Road_User!= '-9']
df[df.Road_User!= '9']

df[df.Speed_Limit > 0 ] #speed limit has to be a positive
df[df.Rigid_Truck_Involvement != '-9' ]
df.head()

,Crash ID,State,Month,Year,Dayweek,Time,Crash_Type,Bus_Involvement,Rigid_Truck_Involvement,Articulated_Truck_Involvement,Speed_Limit,Road_User,Gender,Age
0,20181001,NSW,March,2018,Tuesday,7:18,Multiple vehicle,No,Yes,No,50,Bicyclist (includes pillion passengers),Male,29
1,20181005,NSW,March,2018,Monday,18:25,Multiple vehicle,No,No,No,50,Driver,Male,41
2,20181007,NSW,March,2018,Friday,8:00,Pedestrian,No,No,No,50,Pedestrian,Male,55
3,20181012,NSW,March,2018,Friday,16:05,Multiple vehicle,No,Yes,No,80,Driver,Female,17
4,20181016,NSW,March,2018,Sunday,1:45,Single vehicle,No,No,No,80,Driver,Female,24

In [12]:
# convert Time column to time data
# df['Time'] = pd.to_timedelta(df['Time'])
df['Time'] = pd.to_timedelta(df['Time'].radd('00:')) # ToDo
# df.dtypes

ValueError: only leading negative signs are allowed

In [14]:
# save dataframe as cleaned data 
df.to_csv('data/cleaned_data.csv')

In [ ]:
# plotting
# isolate dtat for two ye